name: Interposer ΔT check

on: [push, pull_request]

jobs:
  deltaT:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Assert ΔT threshold
        run: python -c "import interposer_estimator as ie, sys; d=ie.delta_t(600,2); print(f'DeltaT={d:.2f}'); assert d>=5.0, f'FAIL: ΔT too small ({d})'" 