name: Interposer ΔT check

on: [push, pull_request]

jobs:
  deltaT:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run estimator
        run: |
          python - <<'PY'
from interposer_estimator import delta_t
power, length = 600, 2
dT = delta_t(power, length)
print(f"Computed ΔT = {dT:.2f} °C")
assert dT >= 5.0, f"FAIL: ΔT too small (ΔT={dT:.2f})"
print("PASS: ΔT adequate")
PY 