name: Interposer ΔT check

on: [push, pull_request]

jobs:
  deltaT:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run estimator
        run: |
          python interposer_estimator.py --power_w 600 --trace_len_m 2 > out.txt
          cat out.txt
          python - <<'PY'
import re, sys
with open('out.txt') as f:
    txt = f.read()
m = re.search(r"ΔT = ([0-9.]+)", txt)
assert m and float(m.group(1)) >= 5.0, "FAIL: ΔT too small"
print('PASS: ΔT adequate')
PY 