name: Interposer ΔT check

on: [push, pull_request]

jobs:
  deltaT:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Assert ΔT threshold
        run: |
          python - <<'PY'
          import interposer_estimator as ie
          d = ie.delta_t(600, 2)
          print(f"Computed ΔT = {d:.2f} °C")
          if d < 5.0:
              raise SystemExit(f"FAIL: ΔT too small ({d:.2f})")
          print("PASS: ΔT adequate")
          PY 