name: LedgerOpt check

on: [push, pull_request]

jobs:
  flow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install networkx==3.2
      - name: LedgerOpt vs NetworkX
        run: |
          python ledgeropt.py --json demo_flow.json > out.txt
          echo "LedgerOpt output:" && cat out.txt
          python - <<'PY'
import json, networkx as nx, re, pathlib, sys
with open('demo_flow.json') as f:
    d = json.load(f)
G = nx.DiGraph()
for u,v,c in d['edges']:
    G.add_edge(u, v, capacity=c)
val, _ = nx.maximum_flow(G, d['src'], d['sink'])
with open('out.txt') as f:
    m = re.search(r"(\d+)", f.read())
ledger = int(m.group(1)) if m else None
assert ledger == val, f"Mismatch: LedgerOpt={ledger}, NetworkX={val}"
print(f"PASS: flow={ledger}")
PY 