name: LedgerOpt check

on: [push, pull_request]

jobs:
  flow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install networkx==3.2
      - name: LedgerOpt vs NetworkX
        run: |
          python ledgeropt.py --json demo_flow.json > out.txt
          echo "LedgerOpt output:" && cat out.txt
          python -c "import json, re, networkx as nx, sys; d=json.load(open('demo_flow.json')); G=nx.DiGraph(); [G.add_edge(u,v,capacity=c) for u,v,c in d['edges']]; val,_=nx.maximum_flow(G,d['src'],d['sink']); ledger=int(re.search(r'(\d+)', open('out.txt').read()).group(1)); assert ledger==val, f'Mismatch {ledger}!={val}'; print(f'PASS: flow={ledger}')" 